import type { IconType } from "@icons-pack/react-simple-icons";
import {
  SiAngular,
  SiAnsible,
  SiApachecassandra,
  SiApachekafka,
  SiArgo,
  SiAuth0,
  SiCloudflare,
  SiCockroachlabs,
  SiConsul,
  SiDart,
  SiDatadog,
  SiDigitalocean,
  SiDjango,
  SiDocker,
  SiDotnet,
  SiElasticsearch,
  SiElixir,
  SiEnvoyproxy,
  SiExpress,
  SiFastapi,
  SiFirebase,
  SiFlask,
  SiGit,
  SiGithub,
  SiGitlab,
  SiGo,
  SiGrafana,
  SiGraphql,
  SiHashicorp,
  SiHelm,
  SiHeroku,
  SiInfluxdb,
  SiIstio,
  SiJavascript,
  SiJenkins,
  SiKotlin,
  SiKubernetes,
  SiLaravel,
  SiMongodb,
  SiMysql,
  SiNeo4j,
  SiNestjs,
  SiNetlify,
  SiNextdotjs,
  SiNginx,
  SiNpm,
  SiOpenjdk,
  SiOpenstack,
  SiOpentelemetry,
  SiPacker,
  SiPhp,
  SiPostgresql,
  SiPostman,
  SiPrometheus,
  SiPython,
  SiRabbitmq,
  SiRancher,
  SiReact,
  SiRedis,
  SiRuby,
  SiRubyonrails,
  SiRust,
  SiScala,
  SiSentry,
  SiSpring,
  SiSqlite,
  SiSvelte,
  SiSwift,
  SiTerraform,
  SiTraefikproxy,
  SiTypescript,
  SiVault,
  SiVercel,
  SiVite,
  SiVuedotjs,
  SiWebpack,
} from "@icons-pack/react-simple-icons";

type TechIconMap = ReadonlyMap<string, IconType>;

const TECH_ICONS: TechIconMap = new Map<string, IconType>([
  // Infra / DevOps
  ["docker", SiDocker],
  ["kubernetes", SiKubernetes],
  ["k8s", SiKubernetes],
  ["helm", SiHelm],
  ["terraform", SiTerraform],
  ["ansible", SiAnsible],
  ["jenkins", SiJenkins],
  ["nginx", SiNginx],
  ["traefik", SiTraefikproxy],
  ["consul", SiConsul],
  ["hashicorp", SiHashicorp],
  ["vault", SiVault],
  ["istio", SiIstio],
  ["envoy", SiEnvoyproxy],
  ["packer", SiPacker],
  ["rancher", SiRancher],
  ["prometheus", SiPrometheus],
  ["grafana", SiGrafana],
  ["argocd", SiArgo],
  ["argo", SiArgo],

  // Databases / Data
  ["postgresql", SiPostgresql],
  ["postgres", SiPostgresql],
  ["mysql", SiMysql],
  ["mongodb", SiMongodb],
  ["mongo", SiMongodb],
  ["redis", SiRedis],
  ["elasticsearch", SiElasticsearch],
  ["cassandra", SiApachecassandra],
  ["neo4j", SiNeo4j],
  ["sqlite", SiSqlite],
  ["cockroachdb", SiCockroachlabs],
  ["cockroach", SiCockroachlabs],
  ["kafka", SiApachekafka],
  ["apache-kafka", SiApachekafka],
  ["rabbitmq", SiRabbitmq],
  ["influxdb", SiInfluxdb],

  // Languages
  ["python", SiPython],
  ["javascript", SiJavascript],
  ["js", SiJavascript],
  ["typescript", SiTypescript],
  ["ts", SiTypescript],
  ["go", SiGo],
  ["golang", SiGo],
  ["rust", SiRust],
  ["java", SiOpenjdk],
  ["ruby", SiRuby],
  ["php", SiPhp],
  ["csharp", SiDotnet],
  ["c-sharp", SiDotnet],
  ["dotnet", SiDotnet],
  ["kotlin", SiKotlin],
  ["swift", SiSwift],
  ["dart", SiDart],
  ["elixir", SiElixir],
  ["scala", SiScala],

  // Frameworks
  ["react", SiReact],
  ["vue", SiVuedotjs],
  ["angular", SiAngular],
  ["svelte", SiSvelte],
  ["nextjs", SiNextdotjs],
  ["next", SiNextdotjs],
  ["express", SiExpress],
  ["django", SiDjango],
  ["flask", SiFlask],
  ["spring", SiSpring],
  ["fastapi", SiFastapi],
  ["nestjs", SiNestjs],
  ["rails", SiRubyonrails],
  ["ruby-on-rails", SiRubyonrails],
  ["laravel", SiLaravel],

  // Cloud / Platforms
  ["github", SiGithub],
  ["gitlab", SiGitlab],
  ["vercel", SiVercel],
  ["netlify", SiNetlify],
  ["cloudflare", SiCloudflare],
  ["digitalocean", SiDigitalocean],
  ["heroku", SiHeroku],
  ["firebase", SiFirebase],
  ["openstack", SiOpenstack],

  // Tools
  ["git", SiGit],
  ["npm", SiNpm],
  ["webpack", SiWebpack],
  ["vite", SiVite],
  ["graphql", SiGraphql],
  ["postman", SiPostman],
  ["datadog", SiDatadog],
  ["sentry", SiSentry],
  ["auth0", SiAuth0],
  ["opentelemetry", SiOpentelemetry],
]);

export function resolveTechIconComponent(key: string): IconType | null {
  const normalized = normalizeKey(stripPrefix(key));
  return TECH_ICONS.get(normalized) ?? null;
}

function stripPrefix(key: string): string {
  return key.startsWith("si:") ? key.slice("si:".length) : key;
}

function normalizeKey(input: string): string {
  return input
    .trim()
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "");
}
